name: Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linting-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root

      - name: Lint with pylint
        run: |
          poetry run pylint --load-plugins pylint_quotes tests/* vmm_manager/*

      - name: Test with pytest
        run: |
          poetry run python -m pytest -v
