name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  LintingAndTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root
      - name: Lint with pylint
        run: |
          poetry run pylint tests/* vmm_manager/*
      - name: Test with pytest
        run: |
          poetry run python -m pytest -v
